# Generated by Django 3.2 on 2021-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0002_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='market',
            field=models.CharField(default='', max_length=255),
        ),
    ]
