# Generated by Django 3.2 on 2021-05-03 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0005_auto_20210503_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 23, 50, 41, 8672, tzinfo=utc)),
        ),
    ]
