# Generated by Django 3.2 on 2021-05-04 00:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0006_market_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 0, 52, 25, 850156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
