# Generated by Django 3.2 on 2021-05-04 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0007_auto_20210504_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 1, 9, 14, 214143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
