# Generated by Django 3.2 on 2021-05-17 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0008_auto_20210504_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='upbitconfig',
            name='alter_limit_block',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='upbitconfig',
            name='buy_rate',
            field=models.FloatField(default=-3),
        ),
        migrations.AddField(
            model_name='upbitconfig',
            name='hard_drop',
            field=models.FloatField(default=-3),
        ),
        migrations.AddField(
            model_name='upbitconfig',
            name='new_buy_rate',
            field=models.FloatField(default=-50),
        ),
        migrations.AddField(
            model_name='upbitconfig',
            name='sell_rate',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 12, 21, 20, 142864, tzinfo=utc)),
        ),
    ]
