# Generated by Django 3.2 on 2021-05-18 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0009_auto_20210517_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 11, 21, 12, 14, 571271, tzinfo=utc)),
        ),
    ]
