# Generated by Django 3.2 on 2021-06-18 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0014_auto_20210615_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarket',
            name='change_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinmarket',
            name='change_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinmarket',
            name='opening_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinmarket',
            name='signed_change_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinmarket',
            name='signed_change_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinmarket',
            name='trade_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 7, 25, 15, 325539, tzinfo=utc)),
        ),
    ]
