# Generated by Django 3.2 on 2021-06-18 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0016_auto_20210618_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarket',
            name='bid_min_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coinmarket',
            name='ticker_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 9, 44, 25, 722768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 9, 44, 25, 722299, tzinfo=utc)),
        ),
    ]
