# Generated by Django 3.2 on 2021-06-18 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0017_auto_20210618_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarket',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='coinmarket',
            name='ticker_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 13, 40, 12311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 10, 13, 40, 11839, tzinfo=utc)),
        ),
    ]
