# Generated by Django 3.2 on 2021-06-18 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0018_auto_20210618_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarket',
            name='change_rate_from_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coinmarket',
            name='ticker_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 13, 36, 6, 421797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 13, 36, 6, 421320, tzinfo=utc)),
        ),
    ]
