# Generated by Django 3.2 on 2021-06-18 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0019_auto_20210618_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarket',
            name='last_trade',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 16, 41, 20, 660610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coinmarket',
            name='ticker_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 16, 41, 20, 660575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 16, 41, 20, 660091, tzinfo=utc)),
        ),
    ]
