# Generated by Django 3.2 on 2021-06-23 06:47

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0020_auto_20210618_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='upbitconfig',
            name='btc_market',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upbitconfig',
            name='krw_market',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upbitconfig',
            name='usdt_market',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coinmarket',
            name='last_trade',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coinmarket',
            name='ticker_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='market',
            name='last_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 6, 47, 11, 689234, tzinfo=utc)),
        ),
    ]
