# Generated by Django 3.2 on 2021-07-01 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upbit', '0022_auto_20210625_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 40, 2, 744267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upbitconfig',
            name='buy_rate',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='OrderMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('side', models.CharField(max_length=12)),
                ('ord_type', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('paid_fee', models.FloatField(default=0.0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upbit.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
