# Generated by Django 3.2 on 2021-07-01 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0023_auto_20210701_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 45, 13, 588722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordermarket',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upbit.coinmarket'),
        ),
    ]
