# Generated by Django 3.2 on 2021-07-13 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upbit', '0024_auto_20210701_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='upbitconfig',
            name='reserve_rate',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='market',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 6, 7, 56013, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SellResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.FloatField(default=0.0)),
                ('sell', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
